language: python

python:
  - "3.7"

install:
  - pip install flake8 pylint scapy tornado tox
  - python setup.py install

script:
  - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  - pylint --errors-only wifiphisher
  - tox -e ALL

notifications:
  email:
    on_success: never
    on_failure: always

# FIXME: python-tornado is here because of this error:
#
# > Tornado requires an up-to-date SSL module. This means Python 2.7.9+ or 3.4+
# > (although some distributions have backported the necessary changes to older
# > versions)
#
# Ubuntu does the backporting. The proper solution would be to upgrade Python
# or somehow bypass this Tornado check (or use an older Tornado version
# perhaps?)

addons:
    apt:
        packages:
          - libnl-3-dev
          - libnl-genl-3-dev
          - hostapd
          - dnsmasq
